//
//  SignalEngineCommand.swift
//  MaduraSignalKit
//
//  Created by qiscus on 1/17/17.
//  Copyright © 2017 qiscus. All rights reserved.
//

import Foundation
public protocol SignalEngineCommand {
    /**
     connect to mqtt server.
     */
    func connect()
    /**
     disconnect from mqtt server.
     */
    func disconnect()
    /**
     subscribe to a CallSession.
     - parameters: 
        - callSession: contains unique id that generated by sdk.
     */
    func subscribe(toCallSession callSessionId:String)
    /**
     subscribe to a UserSession. Each user has own `UserSession`.
     - parameters:
        - userSession : an unique identifier from user such as email or phone number.
     */
    func subscribe(toUserSession userId:String)
    /**
     unsubscribe from a CallSession.
     - parameters:
        - callSession: contains unique id that generated by sdk.
     */
    func unsubscribe(fromCallSession callSessionId:String)
    /**
     unsubscribe from a UserSession.
     - parameters:
        - userSession : an unique identifier from user such as email or phone number.
     */
    func unsubscribe(fromUserSession userId:String)
    /**
     publish a call event into CallSession.
     - parameters:
        - callEvent :
        - callSession : contains unique id that generated by sdk.
     */
    func publish(event callEvent:CallEvent, to callSession:String) throws
    /**
     publish an user event into UserSession.
     - parameters:
        - userEvent : 
        - userSession :  an unique identifier from user such as email or phone number.
     */
    func publish(event userEvent:UserEvent, to userSession:String, message callSessionId:String) throws
}
